2022-09-11 16:42:39,030 : INFO : Start of Training
2022-09-11 16:42:39,030 : INFO : Run_id:2022-09-11_164239_295057578
2022-09-11 16:42:39,030 : INFO : Start of Data Load, validation and transformation
2022-09-11 16:42:39,030 : INFO : Start of Archiving Old Rejected Files...
2022-09-11 16:42:39,031 : INFO : End of Archiving Old Rejected Files...
2022-09-11 16:42:39,031 : INFO : Start of Archiving Old Validated Files...
2022-09-11 16:42:39,032 : INFO : End of Archiving Old Validated Files...
2022-09-11 16:42:39,032 : INFO : Start of Archiving Old Processed Files...
2022-09-11 16:42:39,032 : INFO : End of Archiving Old Processed Files...
2022-09-11 16:42:39,032 : INFO : Start of Archiving Old Result Files...
2022-09-11 16:42:39,033 : INFO : End of Archiving Old Result Files...
2022-09-11 16:42:39,033 : INFO : Start of Reading values From Schema...
2022-09-11 16:42:39,033 : INFO : End of Reading values From Schema...
2022-09-11 16:42:39,033 : INFO : Start of Validating Column Length...
2022-09-11 16:42:39,033 : INFO : End of Validating Column Length...
2022-09-11 16:42:39,033 : INFO : Start of Validating Missing Values...
2022-09-11 16:42:39,033 : INFO : End of Validating Missing Values...
2022-09-11 16:42:39,033 : INFO : Start of Replacing Missing Values with NULL...
2022-09-11 16:42:39,033 : INFO : End of Replacing Missing Values with NULL...
2022-09-11 16:42:39,033 : INFO : Start of Creating Table...
2022-09-11 16:42:39,034 : INFO : Opened training database successfully
2022-09-11 16:42:39,035 : INFO : Tables created successfully
2022-09-11 16:42:39,035 : INFO : Closed training database successfully
2022-09-11 16:42:39,035 : INFO : End of Creating Table...
2022-09-11 16:42:39,035 : INFO : Opened training database successfully
2022-09-11 16:42:39,036 : INFO : Start of Inserting Data into Table...
2022-09-11 16:42:39,036 : INFO : End of Inserting Data into Table...
2022-09-11 16:42:39,036 : INFO : Start of Exporting Data into CSV...
2022-09-11 16:42:39,036 : INFO : Opened training database successfully
2022-09-11 16:42:39,037 : INFO : End of Exporting Data into CSV...
2022-09-11 16:42:39,037 : INFO : Start of Moving Processed Files...
2022-09-11 16:42:39,038 : INFO : End of Moving Processed Files...
2022-09-11 16:42:39,038 : INFO : End of Data Load, validation and transformation
2022-09-11 16:42:39,038 : INFO : Start of Preprocessing...
2022-09-11 16:42:39,038 : INFO : Start of reading dataset...
2022-09-11 16:42:39,043 : INFO : End of reading dataset...
2022-09-11 16:42:39,043 : INFO : Start of Dropping Columns...
2022-09-11 16:42:39,050 : INFO : End of Dropping Columns...
2022-09-11 16:42:39,050 : INFO : Start of feature encoding...
2022-09-11 16:42:39,063 : INFO : End of feature encoding...
2022-09-11 16:42:39,063 : INFO : Start of Dropping Columns...
2022-09-11 16:42:39,064 : INFO : End of Dropping Columns...
2022-09-11 16:42:39,064 : INFO : Start of finding missing values...
2022-09-11 16:42:39,065 : INFO : End of finding missing values...
2022-09-11 16:42:39,066 : INFO : Start of splitting features and label ...
2022-09-11 16:42:39,067 : ERROR : Exception raised while splitting features and label:Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomOverSampler.
Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 89, in split_features_label
    self.X_ros, self.y_ros = ros.fit_resample(self.X, self.y)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\imblearn\base.py", line 77, in fit_resample
    X, y, binarize_y = self._check_X_y(X, y)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\imblearn\over_sampling\_random_over_sampler.py", line 150, in _check_X_y
    X, y = self._validate_data(
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\utils\validation.py", line 1074, in check_X_y
    X = check_array(
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\utils\validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomOverSampler.
2022-09-11 16:42:39,072 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 89, in split_features_label
    self.X_ros, self.y_ros = ros.fit_resample(self.X, self.y)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\imblearn\base.py", line 77, in fit_resample
    X, y, binarize_y = self._check_X_y(X, y)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\imblearn\over_sampling\_random_over_sampler.py", line 150, in _check_X_y
    X, y = self._validate_data(
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\utils\validation.py", line 1074, in check_X_y
    X = check_array(
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\utils\validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomOverSampler.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 128, in preprocess_trainset
    self.X, self.y = self.split_features_label(data, label_name='fraude')
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 94, in split_features_label
    raise Exception()
Exception
2022-09-11 16:42:39,072 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 89, in split_features_label
    self.X_ros, self.y_ros = ros.fit_resample(self.X, self.y)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\imblearn\base.py", line 77, in fit_resample
    X, y, binarize_y = self._check_X_y(X, y)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\imblearn\over_sampling\_random_over_sampler.py", line 150, in _check_X_y
    X, y = self._validate_data(
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\base.py", line 596, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\utils\validation.py", line 1074, in check_X_y
    X = check_array(
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\venv\lib\site-packages\sklearn\utils\validation.py", line 909, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 5)) while a minimum of 1 is required by RandomOverSampler.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 128, in preprocess_trainset
    self.X, self.y = self.split_features_label(data, label_name='fraude')
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 94, in split_features_label
    raise Exception()
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\training\train_model.py", line 27, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 133, in preprocess_trainset
    raise Exception
Exception
